### ISSUE TITLE
Smartsheet connector does not check for conditions active state

### ISSUE THREAD

**Issue by TCMMatthiasFankhauser** [ues-io/integrations#34]
# Issue
The functionality added in PR https://github.com/ues-io/integrations/pull/32 allows for conditions to filter for specific rows. In its current form, the conditions however are expected to be always active. Which might not be the case.

## [apps/smartsheet/bundle/bots/load/smartsheet_load/bot.ts](https://github.com/ues-io/integrations/pull/32/files#diff-a637796d3ed1f78e0daea9cd303c70aaeb20dabc9934655a4fd1c5c7fa6bc760)
```
// Transform Conditions on the Uesio Core Id into row Id filters
	const rowIdCondition = conditions?.find(
		(condition) => condition.field === "uesio/core.id"
	)
	if (rowIdCondition) {
		if (rowIdCondition.operator === "IN" && rowIdCondition.values?.length) {
			queryParams.rowIds = rowIdCondition.values.join(",")
		} else if (rowIdCondition.operator === "EQ" && rowIdCondition.value) {
			queryParams.rowIds = rowIdCondition.value
		}
	}

	const queryString = Object.entries(queryParams)
		.map(
			([key, value]) =>
				`${encodeURIComponent(key)}=${encodeURIComponent(`${value}`)}`
		)
		.join("&")

	const url = `https://api.smartsheet.com/2.0/sheets/${collectionMetadata.externalName}?${queryString}`
```

# Proposed solution
In the following piece of code, filter out inactive conditions
```
const rowIdCondition = conditions?.find(
		(condition) => condition.field === "uesio/core.id"
	)
```

**Comment by zachelrath** [comment]
Filtering out inactive conditions is something we're having to do in every single Load Bot. It seems like it should be Uesio's responsibility to filter out inactive Conditions prior to invoking Load Bots, to prevent every Load Bot from having to do this. It's not a big lift, but it's also a bit silly for the Load Bot to spend time filtering out inactive Conditions.

@humandad What do you think? I'm trying to consider edge cases where it would be a problem for us to ONLY send active Conditions to load bots and NOT send inactive conditions. Theoretically in the future we could allow load bots to modify Condition values, but either way it seems a bit pointless for the server to ever see inactive Conditions at all. 

Let's imagine that a Wire has 50 Conditions, i.e. for a lot of crazy Filters. If only one of them is active, then that means we're 
 - Sending 49 inactive Conditions to the server, which is a waste of network bandwidth and processing time
 - Sending 49 inactive Conditions to the Load Bot, which has to remember to filter these out, otherwise it may accidentally be trying to process Conditions which are not active.
 
 It seems like it's asking too much for the author of each Load Bot to have to remember to filter out inactive conditions. 
 
 RIght now we're already asking a lot as part of each Load Bot implementation:
 - Handle fields
 - Handle conditions (of which there are LOTS of types)
 - Handle order
 - Handle pagination
 
Any complexity we can reduce in the Load Bot implementation seems like a win to me.

LMK what you think.

**Comment by zachelrath** [comment]
@abelcloudmasters Would love to hear your thoughts on this as well ^^^. I'd prefer to implement this in Uesio prior to invoking Load Bots so that we don't have to do this in every Load Bot.

**Comment by humandad** [comment]
I think that's fine. The other option would be to provide some nice apis for load bots. That do common tasks. Like "filter conditions". Or "get field map keyed off of external id"

**Comment by ghost** [comment]
@zachelrath When Matti showed me this, the first reaction was this shouldn't be there. Uesio should filter the inactive conditions. I don't see any use case for activating a condition in the integration itself. having a better API as Ben suggests would be painful for the users, at least for this case. `conditions.ExcludeInactive()` feels bad. But I agree with getting a map of keys etc.

**Comment by zachelrath** [comment]
We are resolving this with a change to Uesio to prevent inactive conditions from ever being sent to the server to begin with. Should be available with next Production release.
